# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_sdmem_ip/dist_sdmem_ip.xci
# IP: The module: 'dist_sdmem_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_sdmem_ip/dist_sdmem_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_sdmem_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_sdmem_ip/dist_sdmem_ip.xci
# IP: The module: 'dist_sdmem_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_sdmem_ip/dist_sdmem_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_sdmem_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
