# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ddr_xdc.xdc

# IP: ip/dist_dmem_ip/dist_dmem_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_dmem_ip || ORIG_REF_NAME==dist_dmem_ip} -quiet] -quiet

# IP: ip/dist_ddrmem_ip/dist_ddrmem_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_ddrmem_ip || ORIG_REF_NAME==dist_ddrmem_ip} -quiet] -quiet
