# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/agogow5/ddr/ddr.cache/wt [current_project]
set_property parent.project_path C:/Users/agogow5/ddr/ddr.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/agogow5/ddr/ddr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/agogow5/ddr/ddr.srcs/sources_1/new/CONTROL.v
  C:/Users/agogow5/ddr/ddr.srcs/sources_1/new/ddrmem_controller.v
  C:/Users/agogow5/ddr/ddr.srcs/sources_1/new/sealedDDR.v
  C:/Users/agogow5/ddr/ddr.srcs/sources_1/new/static_cpu.v
  C:/Users/agogow5/ddr/ddr.srcs/sources_1/new/sccomp_dataflow.v
}
read_ip -quiet c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_dmem_ip/dist_dmem_ip.xci
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_dmem_ip/dist_dmem_ip_ooc.xdc]

read_ip -quiet c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_ddrmem_ip/dist_ddrmem_ip.xci
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_ddrmem_ip/dist_ddrmem_ip_ooc.xdc]

read_ip -quiet c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/ddr2_ram/ddr2_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/ddr2_ram/ddr2_ram/user_design/constraints/ddr2_ram.xdc]
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/ddr2_ram/ddr2_ram/user_design/constraints/ddr2_ram_ooc.xdc]

read_ip -quiet c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_sdmem_ip/dist_sdmem_ip.xci
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/dist_sdmem_ip/dist_sdmem_ip_ooc.xdc]

read_ip -quiet c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/agogow5/ddr/ddr.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/agogow5/ddr/ddr.srcs/constrs_1/new/ddr_xdc.xdc
set_property used_in_implementation false [get_files C:/Users/agogow5/ddr/ddr.srcs/constrs_1/new/ddr_xdc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sccomp_dataflow.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
